# Shell variables
# Generated by 'wal'
wallpaper="/home/user/Pictures/wallpapers/atlantis.jpg"

# Special
background='#20222c'
foreground='#c7c7ca'
cursor='#c7c7ca'

# Colors
color0='#20222c'
color1='#A19BAA'
color2='#DFA8AE'
color3='#B8D1B5'
color4='#E3CCB5'
color5='#90AED4'
color6='#96B2D9'
color7='#c7c7ca'
color8='#66697c'
color9='#A19BAA'
color10='#DFA8AE'
color11='#B8D1B5'
color12='#E3CCB5'
color13='#90AED4'
color14='#96B2D9'
color15='#c7c7ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
