--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/user/Pictures/wallpapers/atlantis.jpg"

-- Special
background="#20222c"
foreground="#c7c7ca"
cursor="#c7c7ca"

-- Colors
color0="#20222c"
color1="#A19BAA"
color2="#DFA8AE"
color3="#B8D1B5"
color4="#E3CCB5"
color5="#90AED4"
color6="#96B2D9"
color7="#c7c7ca"
color8="#66697c"
color9="#A19BAA"
color10="#DFA8AE"
color11="#B8D1B5"
color12="#E3CCB5"
color13="#90AED4"
color14="#96B2D9"
color15="#c7c7ca"
