if status is-interactive
    set fish_greeting ""
    starship init fish | source
    alias wallpaper="sh ~/.config/hypr/scipts/choose_wallpaper.sh"
    alias fastfetch2="fastfetch --config ~/.config/fastfetch/config2.jsonc"
    alias relax="mpv --loop-playlist --no-audio-display ~/Music/relax/"
    alias battery="upower -i /org/freedesktop/UPower/devices/battery_BAT1"
    alias tock="./~/.cargo/bin/tock"
    alias c="clear"
    alias n="nvim"
    alias v="vim"
    alias fetch="fastfetch --config examples/8.jsonc"
    alias gc="git clone"
    alias i="yay -S"
    alias s="yay -Ss"
    alias u="yay -Syu"
    alias r="yay -R"
    alias rr="yay -Rns"
    alias phonk="mpv --loop-playlist --no-audio-display ~/Music/phonk/"
    alias py="python"
    alias toipe="./.cargo/bin/toipe"
    alias rm="rm -rf"
    alias cp="cp -r"
end
